language: node_js
node_js:
  - "11"

script:
  - export TZ=Asia/Taipei
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then export NODE_ENV=staging; fi
  - travis_wait 20 yarn generate

deploy:
  - provider: pages
    local-dir: dist/
    skip-cleanup: true
    repo: COSCUP/coscup2019-website-staging
    target-branch: gh-pages
    github-token: $GITHUB_TOKEN
    keep-history: true
    fqdn: staging-2019.coscup.org
    on:
      branch:
        - dev
        - staging
  - provider: pages
    local-dir: dist/
    skip-cleanup: true
    target-branch: gh-pages
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch:
        - master
        - production
