language: node_js
node_js:
  - "11"

script:
  - export TZ=Asia/Taipei
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then export NODE_ENV=staging; fi
  - travis_wait 20 yarn generate

deploy:
  - provider: pages
    local-dir: dist/
    skip-cleanup: true
    repo: COSCUP/coscup2019-website-staging
    target-branch: gh-pages
    github-token: $GITHUB_TOKEN
    keep-history: true
    fqdn: staging-2019.coscup.org
    on:
      branch:
        - dev
        - staging
  - provider: pages
    local-dir: dist/
    skip-cleanup: true
    target-branch: gh-pages
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch:
        - master
        - production

after_deploy:
  - git remote set-url origin https://$GITHUB_TOKEN@github.com/COSCUP/2019.git
  - git fetch origin gh-pages:refs/remotes/origin/gh-pages
  - git config --global user.name "Deployment Bot (from Travis CI)"
  - git config --global user.email "deploy@travis-ci.org"
  - git checkout --orphan gh-pages origin/gh-pages~2
  - git commit -m "Deploy COSCUP/2019 to github.com/COSCUP/2019.git:gh-pages"
  - git cherry-pick origin/gh-pages~2..origin/gh-pages
  - git push -f origin gh-pages
