language: node_js
node_js:
  - "11"

before_install:
  - npm install -g npm@latest

script:
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then NODE_ENV=staging TZ=Asia/Taipei npm run generate; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then TZ=Asia/Taipei npm run generate; fi

deploy:
  - provider: pages
    local-dir: dist/
    skip-cleanup: true
    repo: COSCUP/coscup2019-website-staging
    target-branch: gh-pages
    github-token: $GITHUB_TOKEN
    keep-history: true
    fqdn: staging-2019.coscup.org
    on:
      branch:
        - dev
        - staging
  - provider: pages
    local-dir: dist/
    skip-cleanup: true
    target-branch: gh-pages
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch:
        - master
        - production
